name: Test (production install and build)

on:
  push:
    branches:
      - main
      - next
      - beta
      - io
      - host
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  NODE_ENV: production

jobs:
  production:
    name: Production build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: true
    - name: Install pnpm
      uses: pnpm/action-setup@v5
      with:
        run_install: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: pnpm i --frozen-lockfile
    - name: Check pnpm-lock.yaml
      run: git diff --exit-code pnpm-lock.yaml
    - name: Copy Configure
      run: cp .github/misskey/test.yml .config/default.yml
    - name: Build
      run: pnpm build
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/node@master
      continue-on-error: true
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        args: --all-projects --severity-threshold=medium --sarif-file-output=snyk.sarif
    - name: Upload result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v4
      continue-on-error: true
      with:
        category: Snyk Node.js Vulnerability Scan Result
        sarif_file: snyk.sarif
