name: api.json validation

on:
  push:
    branches:
      - main
      - next
      - beta
      - io
      - host
    paths:
      - packages/backend/**
      - .github/workflows/validate-api-json.yml
  pull_request:
    paths:
      - packages/backend/**
      - .github/workflows/validate-api-json.yml

permissions:
  contents: read

jobs:
  validate-api-json:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: true
    - name: Install pnpm
      uses: pnpm/action-setup@v5
      with:
        run_install: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Install Redocly CLI
      run: npm i -g @redocly/cli
    - run: pnpm i --frozen-lockfile
    - name: Check pnpm-lock.yaml
      run: git diff --exit-code pnpm-lock.yaml
    - name: Copy Configure
      run: cp .config/example.yml .config/default.yml
    - name: Build and generate
      run: pnpm build && pnpm --filter backend generate-api-json
    - name: Validation
      run: npx @redocly/cli lint --extends=minimal ./packages/backend/built/api.json
